import type { Metadata } from 'next';
import { Varela_Round } from 'next/font/google';
import './globals.css';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const varelaRound = Varela_Round({
  subsets: ['latin'], // Correctly specify subsets
  weight: '400', // Make sure the weight matches the available font weights
  variable: '--font-varela-round',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${varelaRound.variable}`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
